name: Social Network

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: social_network
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Set up database
        run: bundle exec rails db:prepare
        env:
          SOCIAL_NETWORK_DATABASE_PASSWORD: postgres
      - name: Run tests
        run: bundle exec rails test
        env:
          RAILS_ENV: test
          SOCIAL_NETWORK_DATABASE_PASSWORD: postgres
